### ISSUE TITLE
Traceback on non-existing pool in DB

### ISSUE THREAD

**Issue by praiskup** [praiskup/resalloc#115]
```
ERROR 2023-03-06 16:00:27,236 PID:68383:139765854164800(Manager) Exception raised in Manager().run()
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/resallocserver/main.py", line 140, in main
    Manager(sync).run()
  File "/usr/lib/python3.11/site-packages/resallocserver/manager.py", line 797, in run
    self._loop()
  File "/usr/lib/python3.11/site-packages/resallocserver/manager.py", line 781, in _loop
    pool.loop(self.sync.ticket)
  File "/usr/lib/python3.11/site-packages/resallocserver/manager.py", line 480, in loop
    self._clean_unknown_resources(event)
  File "/usr/lib/python3.11/site-packages/resallocserver/manager.py", line 601, in _clean_unknown_resources
    last_cleanup = dbinfo.cleaning_unknown_resources
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cleaning_unknown_resources'

```

Seems like the pool instance was not stored in DB?  @nikromen fyi

**Comment by praiskup** [comment]
Closing as duplicate to #128
