### ISSUE TITLE
Wait for postgresql

### ISSUE THREAD

**Issue by xsuchy** [praiskup/resalloc#162]
On copr-be I see in logs during boot:

```
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:     return dialect.connect(*cargs, **cparams)
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:     return self.dbapi.connect(*cargs, **cparams)
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:   File "/usr/lib64/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]: psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or direc>
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:         Is the server running locally and accepting connections on that socket?
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]: The above exception was the direct cause of the following exception:
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]: Traceback (most recent call last):
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:   File "/usr/bin/resalloc-server", line 23, in <module>
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:     main()
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:   File "/usr/lib/python3.12/site-packages/resallocserver/main.py", line 124, in main
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:     init_by_alembic()
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:   File "/usr/lib/python3.12/site-packages/resallocserver/main.py", line 113, in init_by_alembic
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:     alembic.config.main(argv=alembicArgs)
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:   File "/usr/lib/python3.12/site-packages/alembic/config.py", line 630, in main
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:     CommandLine(prog=prog).main(argv=argv)
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:   File "/usr/lib/python3.12/site-packages/alembic/config.py", line 624, in main
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:     self.run_cmd(cfg, options)
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:   File "/usr/lib/python3.12/site-packages/alembic/config.py", line 601, in run_cmd
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:     fn(
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:   File "/usr/lib/python3.12/site-packages/alembic/command.py", line 398, in upgrade
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:     script.run_env()
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:   File "/usr/lib/python3.12/site-packages/alembic/script/base.py", line 579, in run_env
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:     util.load_python_file(self.dir, "env.py")
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:   File "/usr/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
Aug 20 15:35:45 copr-be.aws.fedoraproject.org resalloc-server[1204]:     module = load_module_py(module_id, path)
```

This is not optimal. Reasalloc should be configured to start after PG.

**Comment by praiskup** [comment]
Triage time: Network.taget was done _after_ this traceback (which shouldn't be possible per the *.service)
