### ISSUE TITLE
sqlite database is locked

### ISSUE THREAD

**Issue by praiskup** [praiskup/resalloc#40]
Random test failure against sqlite:
```
 * 3. case: count limit
Traceback (most recent call last):
  File "/builddir/build/BUILD/resalloc-3.1/test-tooling/../bin/resalloc", line 113, in <module>
    sys.exit(main())
  File "/builddir/build/BUILD/resalloc-3.1/test-tooling/../bin/resalloc", line 98, in main
    output = ticket.wait()
  File "/builddir/build/BUILD/resalloc-3.1/resalloc/client.py", line 90, in wait
    return str(self._connection.call("waitTicket", self.id))
  File "/builddir/build/BUILD/resalloc-3.1/resalloc/client.py", line 40, in call
    return fcall(*args)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'sqlalchemy.exc.OperationalError'>:(sqlite3.OperationalError) database is locked\n[SQL: SELECT tickets.id AS tickets_id, tickets.resource_id AS tickets_resource_id, tickets.state AS tickets_state, tickets.tid AS tickets_tid, tickets.sandbox AS tickets_sandbox \nFROM tickets \nWHERE tickets.id = ?]\n[parameters: ('9',)]\n(Background on this error at: http://sqlalche.me/e/e3q8)">
```

**Comment by praiskup** [comment]
I'm running resalloc against sqlute for quite some time in Internal Copr, and seems to be fine now.
